modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "medievalorigins"
version = "1.0.0"
displayName = "Medieval Origins [Forge]"
description = "A Port from Fabric Mod. Medieval Origins is an addon for the Origins mod, focused on the medieval era, with a slight bit of Greek mythology. It contains 15 new Origins."

displayURL = "https://github.com/NunoGomes-Coding/medieval-origins-forge"
authors = "Nuno Gomes"
credits = "Credit goes to Original Fabric author"
logoFile = "icon.png"

[[dependencies.medievalorigins]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"

[[dependencies.medievalorigins]]
modId = "origins"
mandatory = true
versionRange = "[1.19.2-1.5.0.6,)"

[[dependencies.medievalorigins]]
modId = "pehkui"
mandatory = true
versionRange = "[3.4.0,)"